group:
  - files:
      - source: templates/dependabot.yml.j2
        dest: .github/dependabot.yml
        template:
          enable_github_actions: true
    repos: |
      hu553in/hu553in
      hu553in/homebrew-tap
      hu553in/common-things

  - files:
      - source: templates/dependabot.yml.j2
        dest: .github/dependabot.yml
        template:
          enable_github_actions: true
          enable_gitsubmodule: true
    repos: |
      hu553in/personal-website

  - files:
      - source: templates/dependabot.yml.j2
        dest: .github/dependabot.yml
        template:
          enable_github_actions: true
          enable_docker: true
          enable_uv: true
    repos: |
      hu553in/spa-crawler
      hu553in/gdrive-assistant-bot
      hu553in/keenetic-vpn-switcher
      hu553in/grooming-studio-chat-helper
      hu553in/kinescope-io-loader
      hu553in/yandex-alice-openai
      hu553in/dbeaver-gcloud-free

  - files:
      - source: templates/dependabot.yml.j2
        dest: .github/dependabot.yml
        template:
          enable_github_actions: true
          enable_docker: true
          enable_gomod: true
    repos: |
      hu553in/grooming-studio-api
      hu553in/dockguard
      hu553in/telekilogram
      hu553in/tempstream

  - files:
      - source: templates/dependabot.yml.j2
        dest: .github/dependabot.yml
        template:
          enable_github_actions: true
          enable_docker: true
          enable_gradle: true
    repos: |
      hu553in/invites-keycloak

  - files:
      - source: templates/dependabot.yml.j2
        dest: .github/dependabot.yml
        template:
          enable_github_actions: true
          enable_docker: true
          enable_npm: true
    repos: |
      hu553in/grooming-studio
      hu553in/wotd-bot
      hu553in/vrubel-museum-exhibitions
      hu553in/flash-games
      hu553in/cash-bot

  - files:
      - source: templates/dependabot.yml.j2
        dest: .github/dependabot.yml
        template:
          enable_github_actions: true
          enable_docker: true
          enable_uv: true
          extra_docker_directories:
            - "/src/tizen_tool/resources"
    repos: |
      hu553in/tizen-tool

  - files:
      - source: templates/dependabot.yml.j2
        dest: .github/dependabot.yml
        template:
          enable_github_actions: true
          enable_docker: true
          extra_docker_directories:
            - "/playbooks/roles/file_deployment/files/3x_ui"
            - "/playbooks/roles/file_deployment/files/general"
            - "/playbooks/roles/file_deployment/files/grooming"
    repos: |
      hu553in/single-deployment

  - files:
      - source: templates/dependabot.yml.j2
        dest: .github/dependabot.yml
        template:
          enable_github_actions: true
          enable_swift: true
          enable_bundler: true
          swift_ignore_dependencies:
            - swift-transformers
    repos: |
      hu553in/relay
