group:
  - files:
      - source: templates/configs/dependabot.yml.njk
        dest: .github/dependabot.yml
        template:
          enable_github_actions: true
    repos: |
      hu553in/hu553in
      hu553in/homebrew-tap
      hu553in/common-things

  - files:
      - source: templates/configs/dependabot.yml.njk
        dest: .github/dependabot.yml
        template:
          enable_github_actions: true
          enable_gitsubmodule: true
    repos: |
      hu553in/personal-website

  - files:
      - source: templates/configs/dependabot.yml.njk
        dest: .github/dependabot.yml
        template:
          enable_github_actions: true
          enable_docker: true
          enable_uv: true
    repos: |
      hu553in/keenetic-vpn-switcher
      hu553in/grooming-studio-chat-helper
      hu553in/polybot

  - files:
      - source: templates/configs/dependabot.yml.njk
        dest: .github/dependabot.yml
        template:
          enable_github_actions: true
          enable_docker: true
          enable_docker_compose: true
          enable_uv: true
    repos: |
      hu553in/spa-crawler
      hu553in/gdrive-assistant-bot
      hu553in/yandex-alice-openai

  - files:
      - source: templates/configs/dependabot.yml.njk
        dest: .github/dependabot.yml
        template:
          enable_github_actions: true
          enable_uv: true
    repos: |
      hu553in/kinescope-io-loader
      hu553in/dbeaver-gcloud-free

  - files:
      - source: templates/configs/dependabot.yml.njk
        dest: .github/dependabot.yml
        template:
          enable_github_actions: true
          enable_docker: true
          enable_gomod: true
    repos: |
      hu553in/grooming-studio-api
      hu553in/dockguard
      hu553in/telekilogram
      hu553in/swaggerhub-latest-proxy

  - files:
      - source: templates/configs/dependabot.yml.njk
        dest: .github/dependabot.yml
        template:
          enable_github_actions: true
          enable_docker: true
          enable_docker_compose: true
          enable_gomod: true
    repos: |
      hu553in/tempstream

  - files:
      - source: templates/configs/dependabot.yml.njk
        dest: .github/dependabot.yml
        template:
          enable_github_actions: true
          enable_docker_compose: true
          enable_gradle: true
    repos: |
      hu553in/invites-keycloak

  - files:
      - source: templates/configs/dependabot.yml.njk
        dest: .github/dependabot.yml
        template:
          enable_github_actions: true
          enable_docker: true
          enable_npm: true
    repos: |
      hu553in/grooming-studio

  - files:
      - source: templates/configs/dependabot.yml.njk
        dest: .github/dependabot.yml
        template:
          enable_github_actions: true
          enable_npm: true
    repos: |
      hu553in/vrubel-museum-exhibitions
      hu553in/flash-games
      hu553in/gh-workflow-dashboard

  - files:
      - source: templates/configs/dependabot.yml.njk
        dest: .github/dependabot.yml
        template:
          enable_github_actions: true
          enable_npm: true
          enable_cargo: true
          extra_cargo_directories:
            - /src-tauri
    repos: |
      hu553in/relay

  - files:
      - source: templates/configs/dependabot.yml.njk
        dest: .github/dependabot.yml
        template:
          enable_github_actions: true
          enable_docker: true
          enable_uv: true
          extra_docker_directories:
            - /src/tizen_tool/resources
    repos: |
      hu553in/tizen-tool

  - files:
      - source: templates/configs/dependabot.yml.njk
        dest: .github/dependabot.yml
        template:
          enable_github_actions: true
          enable_docker_compose: true
          extra_docker_compose_directories:
            - /playbooks/roles/file_deployment/files/general
            - /playbooks/roles/file_deployment/files/grooming
    repos: |
      hu553in/single-deployment

  - files:
      - source: files/docs/LICENSE
        dest: LICENSE
      - source: files/docs/CONTRIBUTING.md
        dest: CONTRIBUTING.md
      - source: files/docs/CODE_OF_CONDUCT.md
        dest: CODE_OF_CONDUCT.md
    repos: |
      hu553in/invites-keycloak
      hu553in/telekilogram
      hu553in/gdrive-assistant-bot
      hu553in/dockguard
      hu553in/tizen-tool
      hu553in/tempstream
      hu553in/spa-crawler
      hu553in/yandex-alice-openai

  - files:
      - source: files/docs/AGENTS.md
        dest: AGENTS.md
      - source: files/docs/CLAUDE.md
        dest: CLAUDE.md
    repos: |
      hu553in/invites-keycloak
      hu553in/telekilogram
      hu553in/swaggerhub-latest-proxy
      hu553in/dockguard
      hu553in/vrubel-museum-exhibitions
      hu553in/personal-website
      hu553in/grooming-studio-api
      hu553in/grooming-studio
      hu553in/single-deployment
      hu553in/flash-games
      hu553in/gh-workflow-dashboard
      hu553in/tizen-tool
      hu553in/gdrive-assistant-bot
      hu553in/yandex-alice-openai
      hu553in/spa-crawler
      hu553in/grooming-studio-chat-helper
      hu553in/keenetic-vpn-switcher
      hu553in/kinescope-io-loader
      hu553in/dbeaver-gcloud-free
      hu553in/tempstream
      hu553in/relay
      hu553in/polybot

  - files:
      - source: files/configs/.editorconfig
        dest: .editorconfig
      - source: files/configs/.gitattributes
        dest: .gitattributes
    repos: |
      hu553in/invites-keycloak
      hu553in/tizen-tool
      hu553in/gdrive-assistant-bot
      hu553in/yandex-alice-openai
      hu553in/spa-crawler
      hu553in/grooming-studio-chat-helper
      hu553in/keenetic-vpn-switcher
      hu553in/kinescope-io-loader
      hu553in/dbeaver-gcloud-free
      hu553in/vrubel-museum-exhibitions
      hu553in/grooming-studio
      hu553in/flash-games
      hu553in/gh-workflow-dashboard
      hu553in/personal-website
      hu553in/single-deployment
      hu553in/telekilogram
      hu553in/swaggerhub-latest-proxy
      hu553in/tempstream
      hu553in/dockguard
      hu553in/grooming-studio-api
      hu553in/common-things
      hu553in/relay
      hu553in/polybot
