name: Check Bun project

on:
  workflow_call:
    inputs:
      cache_eslint:
        required: false
        type: boolean
        default: false
      playwright:
        required: false
        type: boolean
        default: false
      shfmt:
        required: false
        type: boolean
        default: false

jobs:
  check:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v7
        with:
          persist-credentials: false
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version-file: package.json
      - if: inputs.shfmt
        uses: actions/setup-go@v7
        with:
          go-version: stable
          cache: false
      - if: inputs.shfmt
        uses: hu553in/common-things/.github/actions/setup-shfmt@main
      - run: bun ci
      - if: inputs.cache_eslint
        uses: hu553in/common-things/.github/actions/cache-eslint@main
      - if: inputs.playwright
        uses: actions/cache@v6
        with:
          path: ~/.cache/ms-playwright
          key: playwright|${{ runner.os }}|${{ hashFiles('bun.lock') }}
          restore-keys: |
            playwright|${{ runner.os }}|
      - if: inputs.playwright
        run: bun playwright install-deps chromium
      - run: bun check
      - if: failure() && inputs.playwright
        uses: actions/upload-artifact@v7
        with:
          name: playwright-test-results-${{ github.run_attempt }}
          path: test-results
          if-no-files-found: ignore
